name: release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9
                architecture: 'x64'

            - name: Install requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Build with PyInstaller
              run: |
                python -m PyInstaller dcs-bridge.spec

            - name: Create release
              uses: anton-yurchenko/git-release@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: dist/dcs-bridge.exe

